### ISSUE TITLE
Dalmuir terminating trains can't reach their new route

### ISSUE THREAD

**Issue by Oxalin1** [Railway-Op-Sim/GB-Glasgow-Suburban#1]
Trains scheduled to terminate at Dalmuir Down Siding and start back can't access the correct line for either route out of Dalmuir.
For example, 5L02 is scheduled to turn around at Dalmuir Down Siding and return to Dalmuir, where it forms 2L02. This train then departs towards Singer. The next opportunity to cross to the correct line (without signaller intervention) is at Hyndland - 16 minutes into the journey.

**Comment by zarethrex** [comment]
Added crossover at Dalmuir west
